### ISSUE TITLE
Contribute

### ISSUE THREAD

**Issue by mfirry** [ExaScience/elprep-bench#1]
Hi,

should I want to contribute to the benchmark with either different languages or different implementation, how do I start?

Thanks

-Marco

**Comment by ghost** [comment]
We currently do not intend to accept any pull requests in this repository. The reason for this is that the repository is referenced in our [paper that discusses these benchmarks](https://doi.org/10.1186/s12859-019-2903-5), so we need to keep that reference stable, especially the code.

However, feel free to fork the repository and create your own versions. If you have interesting results, we will gladly link to them from the README. Please ensure that you keep the copyrights in place for versions that are derived from our code.

**Comment by mfirry** [comment]
Cool. Thanks. How can I run these benchmarks? Where are some sample file I can use to test my own implementation?

**Comment by ghost** [comment]
The benchmark that we used in the paper is available in the [elPrep repository](https://github.com/exascience/elprep/tree/v3.04/demo). More specifically, it's the [run-wes-gatk.sh](https://github.com/ExaScience/elprep/blob/v3.04/demo/run-wes-gatk.sh) script.

The script downloads a (pretty large) BAM file that is then processed by elPrep. For testing, you can also run with smaller BAM files. For example, [run-large-gatk.sh](https://github.com/ExaScience/elprep/blob/v3.04/demo/run-large-gatk.sh) uses a somewhat smaller BAM file. Keep in mind, though, that elPrep only makes sense if it can also handle the larger BAM files.

There are some things to watch out for:

- The scripts are for the older version 3 of elPrep and need to be adapted for newer versions (in Go) and for the bench versions (in C++ and Java from this repository). More specifically:

- The run-wes-gatk.sh script uses a Python wrapper to split up the input file into smaller chunks and then processes them separately before merging the partial results again. We don't support that Python wrapper anymore (elPrep version 4 has a better solution for this), and the benchmark in the paper does not run in that mode anyway but runs elPrep directly on the full input file. Instead of executing the Python wrapper, you should just call `elprep filter` (like in run-large-gatk.sh).

- The scripts pass a --nr-of-threads parameter to elPrep. This is a parameter that came from the original Common Lisp version of elPrep. It is not necessary anymore to pass it to the Go version, and the C++ and Java bench versions simply ignore this parameter. C++, Go, Java and their libraries can figure out the optimal number of worker threads on their own without that parameter. (The Go version still recognizes the parameter, which may end up in a suboptimal configuration, so it's better to drop it from the invocation.)

- Finally, the C++ and Java versions only process the (ASCII-based) SAM format, but not the binary BAM format directly. Instead, you have to use [samtools](https://github.com/samtools/samtools) to convert from BAM to SAM, pipe the result into elPrep, and then pipe the output of elPrep into samtools to convert back into BAM format. The full invocation looks similar to this (see  the [samtools manual page](https://www.htslib.org/doc/samtools.html) for details on samtools parameters):
```
 samtools view -h -@$threads $input.bam | \
 elprep filter /dev/stdin /dev/stdout \
    --filter-unmapped-reads \
    --replace-reference-sequences ucsc.hg19.dict \
    --replace-read-group "ID:group1 LB:lib1 PL:illumina PU:unit1 SM:sample1" \
    --mark-duplicates \
    --sorting-order coordinate | \
 samtools view -b -@$threads -o $input.result.bam -                                      
```

- elPrep version 3 and lower internally calls samtools and sets up the proper piping. If you use samtools to pipe into / out of your version of elPrep, please don't compare the performance to elPrep 4 or higher. elPrep 4 or higher process BAM files itself without using any 'outside help', which is more efficient, so the comparison would not be fair.

I hope this helps. Please let me know if you have further questions.

**Comment by mfirry** [comment]
Ok. Thanks a lot. I think I will first try and run the Java benchmark and then write my own implementation so I can compare it to it.

**Comment by mfirry** [comment]
Hi again: haven't been able to understand how to run the Java benchmark. Any help?

**Comment by ghost** [comment]
I'm not exactly sure where you are stuck, but you essentially compile and run this like a regular Java program:
```
git clone https://github.com/exascience/elprep-bench.git
cd elprep-bench/java/
javac *.java -d .
java elprep.elprep filter /dev/stdin /dev/stdout ...
```

The Java version is rudimentary in many ways, including the fact that it only accepts /dev/stdin and /dev/stdout as input and output parameters. You have to use samtools to pipe a BAM file into the Java version of elprep, and pipe the output back into samtools to create the resulting BAM file. I have shown an example in a previous answer, except that instead of calling an elprep binary directly, like in the C++ and Go versions, you have to call java elprep.elprep.

Does this help?

**Comment by mfirry** [comment]
Ah ok. So `javac` and `java`... you don't use any standard tooling like `maven` or `gradle` to manage build and run. That's fine, I guess. Also no external dependencies right? At this point I just need to understand a bit better this `samtools` thing. Thanks so much again!

**Comment by ghost** [comment]
The program is too simple for justifying the overhead of build tools. Yes, there are no external dependencies.
